/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unikommart;

import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Exception
 */
public class FLaporan extends javax.swing.JFrame {
Connection conn;
    /**
     * Creates new form FLaporan
     */
    public FLaporan() {
        initComponents();
        this.setLocationRelativeTo(null);
        conn=koneksi.getConnection();
    }
    FLaporan(String pass){
        initComponents();
        vPegawai.setText(pass);
        vPegawai.setEditable(false);
        this.setLocationRelativeTo(null);
        conn=koneksi.getConnection();   
    }
    void cetakBarang(){
        String reportSource;
        String reportDest;
        Map<String,Object> param=new HashMap<>();
        try{
            reportSource= System.getProperty("user.dir")+"\\Laporan\\Laporan_barang.jrxml";
            reportDest= System.getProperty("user.dir")+"\\Laporan\\Laporan_barang.html";

            JasperReport jasperReport=JasperCompileManager.compileReport(reportSource);

            JasperPrint jasperPrint=JasperFillManager.fillReport(jasperReport,param,conn);

            JasperExportManager.exportReportToHtmlFile(jasperPrint,reportDest);

            JasperViewer.viewReport(jasperPrint,false);

        }catch(JRException e){
            System.out.println(e);
        }
    }
    void cetakTransaksi(){
        String RS;
        String RD;
        Map<String,Object> param=new HashMap<>();
        try{
            RS= System.getProperty("user.dir")+"\\Laporan\\Laporan_transaksi.jrxml";
            RD= System.getProperty("user.dir")+"\\Laporan\\Laporan_transaksi.html";

            JasperReport jasperReport=JasperCompileManager.compileReport(RS);

            JasperPrint jasperPrint=JasperFillManager.fillReport(jasperReport,param,conn);

            JasperExportManager.exportReportToHtmlFile(jasperPrint,RD);

            JasperViewer.viewReport(jasperPrint,false);

        }catch(JRException e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_transaksi = new javax.swing.JLabel();
        btn_barang = new javax.swing.JLabel();
        btn_logout = new javax.swing.JLabel();
        vPegawai = new javax.swing.JTextField();
        btn_laporan_transaksi = new javax.swing.JLabel();
        btn_laporan_barang = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UnikomMart");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseClicked(evt);
            }
        });
        getContentPane().add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 40, 40));

        btn_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_barangMouseClicked(evt);
            }
        });
        getContentPane().add(btn_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 235, 40, 40));

        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 617, 40, 40));

        vPegawai.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        vPegawai.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vPegawai.setBorder(null);
        vPegawai.setOpaque(false);
        vPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vPegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(vPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 96, 60, -1));

        btn_laporan_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_laporan_transaksiMouseClicked(evt);
            }
        });
        getContentPane().add(btn_laporan_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 481, 180, 45));

        btn_laporan_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_laporan_barangMouseClicked(evt);
            }
        });
        getContentPane().add(btn_laporan_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 481, 180, 45));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unikommart/04_Laporan.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_barangMouseClicked
        // TODO add your handling code here:
        new FBarang(vPegawai.getText()).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_barangMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        new FLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void btn_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseClicked
        // TODO add your handling code here:
        new FTransaksi("",vPegawai.getText()).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_transaksiMouseClicked

    private void btn_laporan_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporan_barangMouseClicked
        // TODO add your handling code here:
        cetakBarang();
    }//GEN-LAST:event_btn_laporan_barangMouseClicked

    private void btn_laporan_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporan_transaksiMouseClicked
        // TODO add your handling code here:
        cetakTransaksi();
    }//GEN-LAST:event_btn_laporan_transaksiMouseClicked

    private void vPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vPegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vPegawaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FLaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_barang;
    private javax.swing.JLabel btn_laporan_barang;
    private javax.swing.JLabel btn_laporan_transaksi;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_transaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField vPegawai;
    // End of variables declaration//GEN-END:variables
}
