/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unikommart;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Exception
 */
public class FLogin extends javax.swing.JFrame {
Connection conn;
    /**
     * Creates new form FLogin
     */
    public FLogin() {
        initComponents();
        conn = koneksi.getConnection();
    }
    void cek(){
        try{   
        String sql="Select * from pegawai";
        PreparedStatement st=conn.prepareStatement(sql);
        ResultSet rs = st.executeQuery(); 
        
        String kode,pass,bag;
        while(rs.next()){
            kode=rs.getString("kode_pegawai");
            pass=rs.getString("password");
            bag=rs.getString("bagian").toLowerCase();
            if(vUser.getText().equals(kode.toLowerCase()) || vUser.getText().equals(kode.toUpperCase())){
                if(vPassword.getText().equals(pass)){
                    if(bag.equals("kasir")){
                        new FTransaksi("kasir",kode).setVisible(true);
                        dispose();
                    }else if(bag.equals("admin")){
                        new FTransaksi("",kode).setVisible(true);
                        dispose();
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Password Salah !");
                    break;
                }
            }
        }
        }catch (SQLException sqle) {                  
           System.out.println("Proses Query Gagal = " + sqle);
           System.exit(0);
        }catch(HeadlessException e){
           System.out.println("Koneksi Access Gagal " +e.getMessage());
           System.exit(0);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vUser = new javax.swing.JTextField();
        vPassword = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UnikomMart");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vUser.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        vUser.setBorder(null);
        vUser.setOpaque(false);
        getContentPane().add(vUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 352, 250, 40));

        vPassword.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        vPassword.setBorder(null);
        vPassword.setOpaque(false);
        vPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(vPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 447, 254, 40));

        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 524, 190, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unikommart/01_login.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vPasswordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            cek();
        }
    }//GEN-LAST:event_vPasswordKeyPressed

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
        // TODO add your handling code here:
        cek();
    }//GEN-LAST:event_btn_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField vPassword;
    private javax.swing.JTextField vUser;
    // End of variables declaration//GEN-END:variables
}
